dist: bionic

language: php

php:
  - '7.4'
  - '8.0snapshot'

before_script:
  - composer update --no-interaction --no-progress

script:
  - php vendor/bin/phpspec run -f pretty
  - php vendor/bin/phpcs --standard=PSR12 src/
