dist: bionic

language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - '8.0snapshot'

before_script:
  - composer update --no-interaction --no-progress

script:
  - php bin/phpspec run -f pretty
  - php bin/phpcs --standard=PSR2 src/
